# Generated by Django 3.2.9 on 2021-11-30 10:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Category safe URL')),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='products/images', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Product Name ')),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('slug', models.SlugField(max_length=255, verbose_name='Product safe URL')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Regular price')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Discount price')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cost')),
                ('prod_image', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='products/images', verbose_name='image')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('PRDISNew', models.BooleanField(default=True, verbose_name='New Product ')),
                ('PRDISBestSeller', models.BooleanField(default=False, verbose_name='Best Seller')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-created_at',),
            },
        ),
    ]
